-- -- Totla energy generated by all sites in 6 months
SELECT 'Site 1' AS site, SUM("indregTC1_Energy_kWh_sum") AS total_energy FROM solar_data_site1
UNION ALL
SELECT 'Site 2' AS site, SUM("indregTC2_Energy_kWh_sum") AS total_energy FROM solar_data_site2
UNION ALL
SELECT 'Site 3' AS site, SUM("indregTC3_Energy_kWh_sum") AS total_energy FROM solar_data_site3;

-- Sites1,2 has got same total energy but site 3 has made slightly more energy

SELECT 'Site 1' AS site, AVG("indregTC1_Power_Factor_avg_avg") AS avg_power_factor FROM solar_data_site1
UNION ALL
SELECT 'Site 2' AS site, AVG("indregTC2_Power_Factor_avg_avg") AS avg_power_factor FROM solar_data_site2
UNION ALL
SELECT 'Site 3' AS site, AVG("indregTC3_Power_Factor_avg_avg") AS avg_power_factor FROM solar_data_site3;

SELECT 'site1' AS site, STDDEV("indregTC1_Voltage_LL_V_avg") AS voltage_stability FROM solar_data_site1
UNION ALL
SELECT 'site2' AS site, STDDEV("indregTC2_Voltage_LL_V_avg") AS voltage_stability FROM solar_data_site2
UNION ALL
SELECT 'site2' AS site, STDDEV("indregTC3_Voltage_LL_V_avg") AS voltage_stability FROM solar_data_site3;


SELECT 'site1' AS site, SUM("indregTC1_Power_kW_avg") AS total_power_output FROM solar_data_site1
UNION ALL
SELECT 'site2' AS site, SUM("indregTC2_Power_kW_avg") AS total_power_output FROM solar_data_site2
UNION ALL
SELECT 'site3' AS site, SUM("indregTC3_Power_kW_avg") AS total_power_output FROM solar_data_site3;


SELECT 'site1' AS site, AVG("indregTC1_Current_A_avg") AS avg_current FROM solar_data_site1
UNION ALL
SELECT 'site2' AS site, AVG("indregTC2_Current_A_avg") AS avg_current FROM solar_data_site2
UNION ALL
SELECT 'site3' AS site, AVG("indregTC3_Current_A_avg") AS avg_current FROM solar_data_site3;




SELECT 'site1' AS site, MIN("indregTC1_Voltage_LL_V_avg") AS min_voltage, 
                        MAX("indregTC1_Voltage_LL_V_avg") AS max_voltage
                        FROM solar_data_site1
UNION ALL
SELECT 'site2' AS site, MIN("indregTC2_Voltage_LL_V_avg") AS min_voltage, 
                        MAX("indregTC2_Voltage_LL_V_avg") AS max_voltage
                        FROM solar_data_site2
UNION ALL
SELECT 'site3' AS site, MIN("indregTC3_Voltage_LL_V_avg") AS min_voltage, 
                        MAX("indregTC3_Voltage_LL_V_avg") AS max_voltage
                        FROM solar_data_site3



SELECT AVG("indregTC1_Reactive_Power_kVAR_avg") AS avg_reactive_power FROM solar_data_site1;
SELECT AVG("indregTC2_Reactive_Power_kVAR_avg") AS avg_reactive_power FROM solar_data_site2;
SELECT AVG("indregTC3_Reactive_Power_kVAR_avg") AS avg_reactive_power FROM solar_data_site3;



SELECT 'site1' AS site, AVG("indregTC1_Power_A_kW_avg") AS avg_phase_a_power,
       AVG("indregTC1_Power_B_kW_avg") AS avg_phase_b_power,
       AVG("indregTC1_Power_C_kW_avg") AS avg_phase_c_power
FROM solar_data_site1
UNION ALL
SELECT 'site2' AS site, AVG("indregTC2_Power_A_kW_avg") AS avg_phase_a_power,
       AVG("indregTC2_Power_B_kW_avg") AS avg_phase_b_power,
       AVG("indregTC2_Power_C_kW_avg") AS avg_phase_c_power
FROM solar_data_site2
UNION ALL
SELECT 'site3' AS site, AVG("indregTC3_Power_A_kW_avg") AS avg_phase_a_power,
       AVG("indregTC3_Power_B_kW_avg") AS avg_phase_b_power,
       AVG("indregTC3_Power_C_kW_avg") AS avg_phase_c_power
FROM solar_data_site3;



SELECT 'site1' AS site, (SUM("indregTC1_Energy_kWh_sum") / SUM("indregTC1_Power_kW_avg")) AS energy_utilization_efficiency
FROM solar_data_site1
UNION ALL
SELECT 'site2' AS site, (SUM("indregTC2_Energy_kWh_sum") / SUM("indregTC2_Power_kW_avg")) AS energy_utilization_efficiency
FROM solar_data_site2
UNION ALL
SELECT 'site3' AS site, (SUM("indregTC3_Energy_kWh_sum") / SUM("indregTC3_Power_kW_avg")) AS energy_utilization_efficiency
FROM solar_data_site3;





SELECT 'site1' AS site, DATE_PART('hour', "indregTC1_timestamp") AS hour, 
       SUM("indregTC1_Energy_kWh_sum") AS hourly_energy
FROM solar_data_site1
GROUP BY DATE_PART('hour', "indregTC1_timestamp")
ORDER BY hour;
SELECT 'site2' AS site, DATE_PART('hour', "indregTC2_timestamp") AS hour, 
       SUM("indregTC2_Energy_kWh_sum") AS hourly_energy
FROM solar_data_site2
GROUP BY DATE_PART('hour', "indregTC2_timestamp")
ORDER BY hour;
SELECT 'site3' AS site, DATE_PART('hour', "indregTC3_timestamp") AS hour, 
       SUM("indregTC3_Energy_kWh_sum") AS hourly_energy
FROM solar_data_site3
GROUP BY DATE_PART('hour', "indregTC3_timestamp")
ORDER BY hour;





